---
name: Integration Test
on:
  workflow_call:
    inputs:
      image:
        description: Docker image to test
        required: true
        type: string
jobs:
  integration-test:
    name: Integration Tests
    runs-on: depot-ubuntu-24.04-4
    timeout-minutes: 20
    permissions:
      contents: read
      id-token: write
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Setup Nix
        uses: hoprnet/hopr-workflows/actions/setup-nix@6895dbbc515e39e0e283a68a80b8628ca6ead37a
        with:
          cachix_cache_name: blokli
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Setup GCP
        uses: hoprnet/hopr-workflows/actions/setup-gcp@ac3e0b6137b0ba470a30c373aab2ceba9e0879e4
        with:
          login_artifact_registry: 'true'
          install_sdk: 'false'
      - name: Run Integration tests
        env:
          BLOKLI_TEST_REMOTE_IMAGE: ${{ inputs.image }}
        run: |-
          nix develop -c cargo test --package blokli-integration-tests
